### ISSUE TITLE
Reconsider encode_coordinates interface

### ISSUE THREAD

**Issue by frewsxcv** [georust/polyline#13]
Right now, `encode_coordinates` looks like:

```rust
pub fn encode_coordinates(coordinates: &[[f64; 2]], precision: u32) -> Result<String, String> {
    ...
}
```

We don't need the entire slice at once, we just need anything that can iterate over coordinates:

```rust
pub fn encode_coordinates<C>(coordinates: C, precision: u32) -> Result<String, String>
where
    C: Iterator<Item=[f64; 2]>
{
    ...
}
```

And maybe it makes sense to pull in the `geo-types` crate to reuse our common `Coordinate` construct:

```rust
pub fn encode_coordinates<C, T>(coordinates: C, precision: u32) -> Result<String, String>
where
    C: Iterator<Item=Coordinate<T>>
{
    ...
}
```

**Comment by niclashoyer** [comment]
I added a PR in #16 to tackle this. Please have a look, it might not be idiomatic. More info in the PR.

**Comment by niclashoyer** [comment]
I changed the signature of the `encode_coordinates` to the following:

```rust
pub fn encode_coordinates<C>(coordinates: C, precision: u32) -> Result<String, String>
where
    C: IntoIterator<Item=Coordinate<f64>>,
```

By using `IntoIterator` this is more convenient when using types such as `LineString`:

```rust
let coords = line_string![(x: 2.0, y: 1.0), (x: 4.0, y: 3.0)];
let encoded_vec = polyline::encode_coordinates(coords, 5).unwrap();
```
