### ISSUE TITLE
crates publishing team

### ISSUE THREAD

**Issue by michaelkirk** [georust/polyline#22]
👋 Hi @tmcw, you are the only "user-owner" of the [polyline crate on crates.io](https://crates.io/crates/polyline), so only you can edit that crate's owners on crates.io.

Following up on https://github.com/georust/meta/pull/21, I created a new [polyline-publishers team](https://github.com/orgs/georust/teams/polyline-publishers) for publishing to crates.io with you as maintainer. 

Could you please [update the crate owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)? Specifically:

---

- [x] update **polyline crate** owners on crates.io:

```
cd polyline

# 💥 remove large publishing group
cargo owner --remove github:georust:core

# 🔐 add small publishing group
cargo owner --add github:georust:polyline-publishers

# you're currently the only user-owner of the crate. Consider adding another user-owner, 
# that way if for some reason you become inaccessible we have someone else who can edit the owners. 
# See https://github.com/rust-lang/crates.io/issues/2906
cargo owner --add <username>

# make sure everything looks good 👀 
cargo owner --list
```
---

If there's anyone else you'd like to be able to publish the crate, feel free to add them to your publishing team, or as a user-owner. Consider that user-owners, as opposed to owners-via-team, can themselves edit the crate's owners, which could be desirable, or not, depending.

In particular, it looks like @urschrei has been actively contributing to GH. Once you switch the publishing team, @urschrei (or anyone else) won't be able to publish until either they are added back to the publishing team or added as a user owner.

Let me know if you have any questions, or you can review https://github.com/georust/meta/pull/21.

**Comment by tmcw** [comment]
👍 Done, and I've added you and Stephan as owners.

**Comment by michaelkirk** [comment]
Excellent, thank you for responding so promptly. 

Closing this issue.
