### ISSUE TITLE
Error handling of bad polyline still broken

### ISSUE THREAD

**Issue by urschrei** [georust/polyline#39]
Our fix in #37 has not worked: trying to decode the polyline `'ugh_ugh'` gives an out of bounds error on [line 142](https://github.com/georust/polyline/blob/bb74f6bfaa18e91ca504b1377ad02291e8d7eb09/src/lib.rs#L142):

`index out of bounds: the len is 7 but the index is 7`.

**Comment by urschrei** [comment]
cc @mattiZed

**Comment by urschrei** [comment]
Repro (note ommission of `should_panic` directive on the test: we want to ensure that error values and panics are surfaced, and we want to distinguish between them, since we can handle errors, but not panics). We expect this test to return an `Err` value, but we have a logic error in our loop beginning on line 141:

```rust
#[test]
fn invalid_string() {
    let s = "ugh_ugh";
    let expected: Result<_, _> = Err("Cannot decode character at index 12".to_string());
    assert_eq!(decode_polyline(s, 5), expected);
}
```

**Comment by mattiZed** [comment]
Well then, I guess it's time to actually understand and fix the algorithm instead of suppressing the symptoms - I might have a bit of free time for this next week as my org also relies on this crate in some sense.
